plugins { id 'com.android.application' }

android {
    namespace 'com.tinta.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.tinta.app'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
}
